#GLOBAL VARIABLES
remote_user: mj

# Elastic Search Repo
elastic_repo: elasticsearch.repo

# influxdb repo
influxdb_repo: influxdb.repo

# grafana repo
grafana_repo: grafana.repo

# Logstash conf
logstash_conf: logstash.conf

# Prometheus
prometheus_src: prometheus.service

# Nagios User and Pass
nagios_user: nagiosadmin
nagios_pass: 09170113

# LAMP Variables
domain: mj
owner: mj
group: mj
index_html: index.html
ubuntu_src: mj-ubuntu.conf
centos_src: mj-centos.conf
